name: Nancy.Plots.ScottPlot-pack-release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths: 
      - 'Nancy/Nancy.Plots/Nancy.Plots.ScottPlot/Nancy.Plots.ScottPlot.csproj'
  pull_request:
    branches:
      - master
    paths: 
      - 'Nancy/Nancy.Plots/Nancy.Plots.ScottPlot/Nancy.Plots.ScottPlot.csproj'

jobs:
  Nancy-Plots-ScottPlot-pack-release:
    runs-on: ubuntu-latest
    
    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "Nancy/Nancy.Plots/Nancy.Plots.sln"
      NANCY_PLOTS_SCOTTPLOT: "Nancy/Nancy.Plots/Nancy.Plots.ScottPlot/Nancy.Plots.ScottPlot.csproj"
      NANCY_PLOTS_SCOTTPLOT_TESTS: "Nancy/Nancy.Plots/Nancy.Plots.ScottPlot.Tests/Nancy.Plots.ScottPlot.Tests.csproj"
      NANCY_PLOTS_SCOTTPLOT_PACKS: "Nancy/Nancy.Plots/Nancy.Plots.ScottPlot/bin/Release/**/*.nupkg"

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Build Nancy.Plots.ScottPlot
        run: dotnet build $NANCY_PLOTS_SCOTTPLOT --configuration $BUILD_CONFIG

      - name: Build Nancy.Plots.ScottPlot.Tests
        run: dotnet build $NANCY_PLOTS_SCOTTPLOT_TESTS --configuration $BUILD_CONFIG

      - name: Test Nancy.Plots.ScottPlot
        run: dotnet test $NANCY_PLOTS_SCOTTPLOT_TESTS /p:Configuration=$BUILD_CONFIG

      - name: Pack
        run: dotnet pack $NANCY_PLOTS_SCOTTPLOT --configuration $BUILD_CONFIG --no-restore --no-build

      - name: Publish
        run: dotnet nuget push $NANCY_PLOTS_SCOTTPLOT_PACKS --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}
